<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-72CGLFOI" failures="2" tests="6" name="Test" time="0.185" errors="0" timestamp="2020-03-24T16:42:59 IST">
  <testcase classname="onlineclass.LearningAttributesinTestNG" name="TestB" time="0.037">
    <failure type="java.lang.AssertionError" message="expected [yahoo] but found [yahoo1]">
      <![CDATA[java.lang.AssertionError: expected [yahoo] but found [yahoo1]
at onlineclass.LearningAttributesinTestNG.TestB(LearningAttributesinTestNG.java:13)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- TestB -->
  <testcase classname="onlineclass.LearningAttributesinTestNG" name="TestC" time="0.004"/>
  <testcase classname="onlineclass.LearningAttributesinTestNG" name="TestA" time="0.009"/>
  <testcase classname="onlineclass.Sample2" name="TestA" time="0.013"/>
  <testcase classname="onlineclass.Sample2" name="TestB" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [yahoo] but found [yahoo1]">
      <![CDATA[java.lang.AssertionError: expected [yahoo] but found [yahoo1]
at onlineclass.Sample2.TestB(Sample2.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- TestB -->
  <testcase classname="onlineclass.Sample2" name="TestC" time="0.009"/>
</testsuite> <!-- Test -->
